version: "3.7"

networks:
  servicemesh: {}

services:
  frontend-proxy:
    container_name: frontend-proxy
    image: frontend-proxy:latest
    build:
      context: services
      dockerfile: Dockerfile-envoyproxy
    networks:
    - servicemesh
    ports:
    - "8080:8080"
    - "8443:8443"
    - "9901:9901"
    depends_on:
    - "users-service"
    - "tasks-service"

  users-service:
    container_name: users-service
    image: users-service:latest
    build:
      context: services/flask/users-service
      dockerfile: Dockerfile
    networks:
    - servicemesh
    depends_on:
    - "tasks-service"
    environment:
    - SERVICE_NAME='users-service'

  tasks-service:
    container_name: tasks-service
    image: tasks-service:latest
    build:
      context: services/flask/tasks-service
      dockerfile: Dockerfile
    networks:
    - servicemesh
    environment:
    - SERVICE_NAME='tasks-service'

  mongodb:
    image: mongo
    container_name: mongodb
    restart: always
    networks:
    - servicemesh
    ports:
    - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      PUID: 1000
      PGID: 1000

  prometheus:
    container_name: prometheus
    image: prom/prometheus:v2.2.1
    volumes:
    - ./services/config/prometheus-config.yaml:/etc/prometheus/prometheus.yml
    networks:
    - servicemesh
    ports:
    - "9090:9090"
    depends_on:
    - "frontend-proxy"

  grafana:
    image: grafana/grafana:5.1.0
    volumes:
      - ./services/config/grafana/config.ini:/etc/grafana/grafana.ini
      - ./services/config/grafana/datasource.yaml:/etc/grafana/provisioning/datasources/default.yaml
      - ./services/config/grafana/dashboard.yaml:/etc/grafana/provisioning/dashboards/default.yaml
      - ./services/config/grafana/dashboards:/var/lib/grafana/dashboards
    ports:
      - 3000:3000
    depends_on:
      - prometheus