version: "3.7"

networks:
  servicemesh: {}

services:
  frontend-proxy:
    container_name: frontend-proxy
    image: envoyproxy/envoy:v1.21-latest
    build:
      context: services
      dockerfile: Dockerfile-envoyproxy
    volumes:
    - ./config/envoy:/etc/envoy 
    networks:
    - servicemesh
    ports:
    - "8080:8080"
    - "8443:8443"
    - "9901:9901"
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: frontend-proxy
    depends_on:
    - "users-service"
    - "tasks-service"

  users-service:
    container_name: users-service
    image: users-service:latest
    build:
      context: services/flask/users-service
      dockerfile: Dockerfile
    networks:
    - servicemesh
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: users-service
    depends_on:
    - "tasks-service"
    environment:
    - SERVICE_NAME='users-service'

  tasks-service:
    container_name: tasks-service
    image: tasks-service:latest
    build:
      context: services/flask/tasks-service
      dockerfile: Dockerfile
    networks:
    - servicemesh
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: tasks-service
    depends_on:
    - "fluentd"
    environment:
    - SERVICE_NAME='tasks-service'

  mongodb:
    image: mongo
    container_name: mongodb
    restart: always
    networks:
    - servicemesh
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: mongodb
    ports:
    - 27017:27017
    depends_on:
    - "fluentd"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      PUID: 1000
      PGID: 1000

  fluentd:
    image: fluent/fluentd:v0.12
    container_name: fluentd
    volumes:
    - ./output:/output
    - ./config/fluentd:/fluentd/etc
    networks:
    - servicemesh
    ports:
    - "24224:24224"
    - "24224:24224/udp"
    logging:
      driver: "json-file"
      options:
        max-size: 100m
        max-file: "5"