version: "3.7"

volumes:
    grafana_data: {}

services:
  frontend-proxy:
    build:
      context: .
      dockerfile: Dockerfile-envoyproxy
    networks:
    - servicemesh
    ports:
    - "8080:8080"
    - "9901:9901"
    depends_on:
    - "film-service"
    - "rating-service"
  film-service:
    build:
      context: .
      dockerfile: Dockerfile-film
    networks:
    - servicemesh
    depends_on:
    - "rating-service"
    environment:
    - SERVICE_NAME='film-service'
  rating-service:
    build:
      context: .
      dockerfile: Dockerfile-rating
    networks:
    - servicemesh
    environment:
    - SERVICE_NAME='rating-service'
  prometheus:
    build:
      context: .
      dockerfile: Dockerfile-prometheus
    command: --config.file=/prometheus/prometheus.yaml --log.level=debug
    networks:
    - servicemesh
    ports:
    - "9090:9090"
    depends_on:
    - "frontend-proxy"
  grafana:
    image: grafana/grafana:latest
    user: "472"
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning/datasources/:/etc/grafana/provisioning/datasources/
    env_file:
      - ./grafana/config.monitoring

networks:
    servicemesh: {}
