# syntax=docker/dockerfile:1

FROM python:3.7
RUN pip3 install -q Flask requests pymongo

WORKDIR /users-service-docker
COPY ./flask/users/users_service.py /users-service-docker/users_service.py
CMD [ "python3", "/users-service-docker/users_service.py"]