version: "3.7"

services:
  frontend-proxy:
    image: frontend-proxy:latest
    build:
      context: Dockerfiles
      dockerfile: Dockerfile-envoyproxy
    networks:
    - servicemesh
    ports:
    - "8080:8080"
    - "9901:9901"
    depends_on:
    - "film-service"
    - "rating-service"
  film-service:
    image: film-service:latest
    build:
      context: Dockerfiles
      dockerfile: Dockerfile-film
    networks:
    - servicemesh
    depends_on:
    - "rating-service"
    environment:
    - SERVICE_NAME='film-service'
  rating-service:
    image: rating-service:latest
    build:
      context: Dockerfiles
      dockerfile: Dockerfile-rating
    networks:
    - servicemesh
    environment:
    - SERVICE_NAME='rating-service'
  jaeger:
    image: jaegertracing/all-in-one
    environment:
    - COLLECTOR_ZIPKIN_HOST_PORT=9411
    networks:
    - servicemesh
    ports:
    - "9411:9411"
    - "16686:16686"

networks:
    servicemesh: {}
