# syntax=docker/dockerfile:1

FROM envoyproxy/envoy-alpine-dev:latest
WORKDIR /fileService-docker

RUN apk update && apk add py3-pip bash curl
RUN pip3 install -q Flask==0.11.1 requests==2.18.4
COPY ./flask/films.py /fileService-docker/films.py

CMD [ "python3", "/fileService-docker/films.py"]
