global:
  scrape_interval: 5s

  external_labels:
    monitor: "microservice-playground"

rule_files:

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["prometheus:9090"]

  # These are the metrics from the frontend proxy. The proxy is envoy.
  # The prometheus metrics are available on port 9901
  - job_name: 'frontend-proxy'
    metrics_path: '/stats/prometheus'
    scrape_interval: 5s
    static_configs:
    - targets: ['frontend-proxy:9901']

  - job_name: "app"
    static_configs:
      - targets: [ "app:5000" ]

  - job_name: "users-services"
    static_configs:
      - targets: ["users-service:5000"]

  - job_name: "tasks-service"
    static_configs:
      - targets: ["tasks-service:6000"]
