# syntax=docker/dockerfile:1

FROM python:3.7
RUN pip3 install -q Flask==1.1.1 requests py_zipkin==0.20.0

WORKDIR /filmService-docker
COPY ./flask/films.py /filmService-docker/films.py
CMD [ "python3", "/filmService-docker/films.py"]
